server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-fpsukpc8eq-stack-awsebrdsdatabase-zutvabdtsbeu.c9u2woqckzt9.ap-southeast-1.rds.amazonaws.com:5432/alamsn317
    driver-class-name: org.postgresql.Driver
    username: alamsn317
    password: alamsn317
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
